### ISSUE TITLE
Converter only writes transactions with type TRANSFER

### ISSUE THREAD

**Issue by Niek** [gerwin3/revolut-to-mt940#1]
See below:
```bash
→ cat ~/Downloads/revolut.csv | wc -l
      56
→ grep -c TRANSFER ~/Downloads/revolut.csv
7
→ python3 main.py --in ~/Downloads/revolut.csv --out ~/Downloads/revolut.mt940 --account-iban -SNIP-
Wrote 7 transactions to file: /Users/niek/Downloads/revolut.mt940.
```
It seems only transactions with type `TRANSFER` are written. Not sure if this is a bug or on purpose, but for a full export the other types (`TOPUP`, `CARD_PAYMENT`, `CARD_REFUND`, etc - see [here](https://developer.revolut.com/api-reference/business/#operation/getTransactions)) should be supported too.

On a side-note, the BIC of Revolut is now `REVOLT21` :)

**Comment by gerwin3** [comment]
Thanks for reporting :)

Turns out it was actually a bug with counting the number of transactions. It would always say 7. Fixed now.

You can check whether the number of output transactions is correct by inspecting the mt940 file, just count the number of lines that start with `:86:`.

**Comment by Niek** [comment]
Ah, you are correct - I didn't check the generated file in detail. Thanks for the script!

**Comment by Niek** [comment]
Hmm, the script generates 60 transactions while the CSV has 55 lines + 1 header line - something looks odd (*edit*: I see that's because the fees are added separately).

When importing in Jortt I get an error that the "De controle bedragen in het MT940 bestand komen niet overeen met het totaal van de transacties." - will try to go through the file and see what's wrong. *Edit*: it seems this is because I have a EUR and USD account, and it mixes the amounts resulting in wrong totals.

**Comment by gerwin3** [comment]
> Edit: it seems this is because I have a EUR and USD account, and it mixes the amounts resulting in wrong totals.

I only tested in on EUR accounts, so that could definitely be it! I'm not really sure how to fix that. I do think that technically those are two separate accounts for the purposes of bookkeeping. You could create two bank accounts for them in your bookkeeping software and export separate CSV files from Revolut as well (I think Revolut will actually export the cross transfers and in that case it should work).
